Final HTML after Validation.
Error: The frameborder attribute on the iframe element is obsolete. Use CSS instead.
From line 118, column 9; to line 120, column 73
>↩        <iframe width="400" height="315" src="https://www.youtube.com/embed/ojcNcvb1olg?si=diVPVCi14LYUhtLU" ↩        title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" ↩        referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></ifra

CORRECTION
frameborder="0" changed to style="border": none;